# Generated by Django 3.0.4 on 2020-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200319_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.IntegerField(choices=[(0, 'EsztiDi')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_updated',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True), verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(help_text='A short summary of the issue', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='details',
            field=models.TextField(verbose_name='More details'),
        ),
    ]
