# Generated by Django 3.0.4 on 2020-04-24 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_auto_20200323_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, null=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
