# Generated by Django 3.0.4 on 2020-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200319_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.IntegerField(blank=True, choices=[(1, 'EsztiDi'), (2, 'Guest')], null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
