# Generated by Django 3.0.4 on 2020-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200320_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.IntegerField(choices=[(0, '-'), (1, 'EsztiDi')], default=0),
        ),
    ]
